"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class region_3d_t(object):
    __slots__ = ["center", "size"]

    def __init__(self):
        self.center = [ 0.0 for dim0 in range(3) ]
        self.size = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(region_3d_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.center[:3]))
        buf.write(struct.pack('>3d', *self.size[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != region_3d_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return region_3d_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = region_3d_t()
        self.center = struct.unpack('>3d', buf.read(24))
        self.size = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if region_3d_t in parents: return 0
        tmphash = (0x94830fc8d7404191) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if region_3d_t._packed_fingerprint is None:
            region_3d_t._packed_fingerprint = struct.pack(">Q", region_3d_t._get_hash_recursive([]))
        return region_3d_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

