// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/lcmtypes_region_3d_t.h"

static int __lcmtypes_region_3d_t_hash_computed;
static uint64_t __lcmtypes_region_3d_t_hash;

uint64_t __lcmtypes_region_3d_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __lcmtypes_region_3d_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__lcmtypes_region_3d_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x94830fc8d7404191LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __lcmtypes_region_3d_t_get_hash(void)
{
    if (!__lcmtypes_region_3d_t_hash_computed) {
        __lcmtypes_region_3d_t_hash = (int64_t)__lcmtypes_region_3d_t_hash_recursive(NULL);
        __lcmtypes_region_3d_t_hash_computed = 1;
    }

    return __lcmtypes_region_3d_t_hash;
}

int __lcmtypes_region_3d_t_encode_array(void *buf, int offset, int maxlen, const lcmtypes_region_3d_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].center, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].size, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int lcmtypes_region_3d_t_encode(void *buf, int offset, int maxlen, const lcmtypes_region_3d_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmtypes_region_3d_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __lcmtypes_region_3d_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __lcmtypes_region_3d_t_encoded_array_size(const lcmtypes_region_3d_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(p[element].center, 3);

        size += __double_encoded_array_size(p[element].size, 3);

    }
    return size;
}

int lcmtypes_region_3d_t_encoded_size(const lcmtypes_region_3d_t *p)
{
    return 8 + __lcmtypes_region_3d_t_encoded_array_size(p, 1);
}

int __lcmtypes_region_3d_t_decode_array(const void *buf, int offset, int maxlen, lcmtypes_region_3d_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].center, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].size, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __lcmtypes_region_3d_t_decode_array_cleanup(lcmtypes_region_3d_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(p[element].center, 3);

        __double_decode_array_cleanup(p[element].size, 3);

    }
    return 0;
}

int lcmtypes_region_3d_t_decode(const void *buf, int offset, int maxlen, lcmtypes_region_3d_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmtypes_region_3d_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __lcmtypes_region_3d_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmtypes_region_3d_t_decode_cleanup(lcmtypes_region_3d_t *p)
{
    return __lcmtypes_region_3d_t_decode_array_cleanup(p, 1);
}

int __lcmtypes_region_3d_t_clone_array(const lcmtypes_region_3d_t *p, lcmtypes_region_3d_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(p[element].center, q[element].center, 3);

        __double_clone_array(p[element].size, q[element].size, 3);

    }
    return 0;
}

lcmtypes_region_3d_t *lcmtypes_region_3d_t_copy(const lcmtypes_region_3d_t *p)
{
    lcmtypes_region_3d_t *q = (lcmtypes_region_3d_t*) malloc(sizeof(lcmtypes_region_3d_t));
    __lcmtypes_region_3d_t_clone_array(p, q, 1);
    return q;
}

void lcmtypes_region_3d_t_destroy(lcmtypes_region_3d_t *p)
{
    __lcmtypes_region_3d_t_decode_array_cleanup(p, 1);
    free(p);
}

int lcmtypes_region_3d_t_publish(lcm_t *lc, const char *channel, const lcmtypes_region_3d_t *p)
{
      int max_data_size = lcmtypes_region_3d_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = lcmtypes_region_3d_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _lcmtypes_region_3d_t_subscription_t {
    lcmtypes_region_3d_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void lcmtypes_region_3d_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    lcmtypes_region_3d_t p;
    memset(&p, 0, sizeof(lcmtypes_region_3d_t));
    status = lcmtypes_region_3d_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding lcmtypes_region_3d_t!!!\n", status);
        return;
    }

    lcmtypes_region_3d_t_subscription_t *h = (lcmtypes_region_3d_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    lcmtypes_region_3d_t_decode_cleanup (&p);
}

lcmtypes_region_3d_t_subscription_t* lcmtypes_region_3d_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    lcmtypes_region_3d_t_handler_t f, void *userdata)
{
    lcmtypes_region_3d_t_subscription_t *n = (lcmtypes_region_3d_t_subscription_t*)
                       malloc(sizeof(lcmtypes_region_3d_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 lcmtypes_region_3d_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg lcmtypes_region_3d_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int lcmtypes_region_3d_t_subscription_set_queue_capacity (lcmtypes_region_3d_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int lcmtypes_region_3d_t_unsubscribe(lcm_t *lcm, lcmtypes_region_3d_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe lcmtypes_region_3d_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

