/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class edge_t implements lcm.lcm.LCMEncodable
{
    public lcmtypes.vertex_t vertex_src;
    public lcmtypes.vertex_t vertex_dst;
    public lcmtypes.trajectory_t trajectory;
 
    public edge_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1fae492d71eedf94L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.edge_t.class))
            return 0L;
 
        classes.add(lcmtypes.edge_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + lcmtypes.vertex_t._hashRecursive(classes)
             + lcmtypes.vertex_t._hashRecursive(classes)
             + lcmtypes.trajectory_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.vertex_src._encodeRecursive(outs); 
 
        this.vertex_dst._encodeRecursive(outs); 
 
        this.trajectory._encodeRecursive(outs); 
 
    }
 
    public edge_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public edge_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.edge_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.edge_t o = new lcmtypes.edge_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.vertex_src = lcmtypes.vertex_t._decodeRecursiveFactory(ins);
 
        this.vertex_dst = lcmtypes.vertex_t._decodeRecursiveFactory(ins);
 
        this.trajectory = lcmtypes.trajectory_t._decodeRecursiveFactory(ins);
 
    }
 
    public lcmtypes.edge_t copy()
    {
        lcmtypes.edge_t outobj = new lcmtypes.edge_t();
        outobj.vertex_src = this.vertex_src.copy();
 
        outobj.vertex_dst = this.vertex_dst.copy();
 
        outobj.trajectory = this.trajectory.copy();
 
        return outobj;
    }
 
}

