/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class environment_t implements lcm.lcm.LCMEncodable
{
    public lcmtypes.region_3d_t operating;
    public lcmtypes.region_3d_t goal;
    public int num_obstacles;
    public lcmtypes.region_3d_t obstacles[];
 
    public environment_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8caabc2a2ba0f9c7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.environment_t.class))
            return 0L;
 
        classes.add(lcmtypes.environment_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + lcmtypes.region_3d_t._hashRecursive(classes)
             + lcmtypes.region_3d_t._hashRecursive(classes)
             + lcmtypes.region_3d_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.operating._encodeRecursive(outs); 
 
        this.goal._encodeRecursive(outs); 
 
        outs.writeInt(this.num_obstacles); 
 
        for (int a = 0; a < this.num_obstacles; a++) {
            this.obstacles[a]._encodeRecursive(outs); 
        }
 
    }
 
    public environment_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public environment_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.environment_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.environment_t o = new lcmtypes.environment_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.operating = lcmtypes.region_3d_t._decodeRecursiveFactory(ins);
 
        this.goal = lcmtypes.region_3d_t._decodeRecursiveFactory(ins);
 
        this.num_obstacles = ins.readInt();
 
        this.obstacles = new lcmtypes.region_3d_t[(int) num_obstacles];
        for (int a = 0; a < this.num_obstacles; a++) {
            this.obstacles[a] = lcmtypes.region_3d_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public lcmtypes.environment_t copy()
    {
        lcmtypes.environment_t outobj = new lcmtypes.environment_t();
        outobj.operating = this.operating.copy();
 
        outobj.goal = this.goal.copy();
 
        outobj.num_obstacles = this.num_obstacles;
 
        outobj.obstacles = new lcmtypes.region_3d_t[(int) num_obstacles];
        for (int a = 0; a < this.num_obstacles; a++) {
            outobj.obstacles[a] = this.obstacles[a].copy();
        }
 
        return outobj;
    }
 
}

