/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class region_3d_t implements lcm.lcm.LCMEncodable
{
    public double center[];
    public double size[];
 
    public region_3d_t()
    {
        center = new double[3];
        size = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x94830fc8d7404191L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.region_3d_t.class))
            return 0L;
 
        classes.add(lcmtypes.region_3d_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.center[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.size[a]); 
        }
 
    }
 
    public region_3d_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public region_3d_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.region_3d_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.region_3d_t o = new lcmtypes.region_3d_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.center = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.center[a] = ins.readDouble();
        }
 
        this.size = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.size[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.region_3d_t copy()
    {
        lcmtypes.region_3d_t outobj = new lcmtypes.region_3d_t();
        outobj.center = new double[(int) 3];
        System.arraycopy(this.center, 0, outobj.center, 0, 3); 
        outobj.size = new double[(int) 3];
        System.arraycopy(this.size, 0, outobj.size, 0, 3); 
        return outobj;
    }
 
}

