/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class vertex_t implements lcm.lcm.LCMEncodable
{
    public lcmtypes.state_t state;
 
    public vertex_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x780573746198cdacL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.vertex_t.class))
            return 0L;
 
        classes.add(lcmtypes.vertex_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + lcmtypes.state_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.state._encodeRecursive(outs); 
 
    }
 
    public vertex_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public vertex_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.vertex_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.vertex_t o = new lcmtypes.vertex_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.state = lcmtypes.state_t._decodeRecursiveFactory(ins);
 
    }
 
    public lcmtypes.vertex_t copy()
    {
        lcmtypes.vertex_t outobj = new lcmtypes.vertex_t();
        outobj.state = this.state.copy();
 
        return outobj;
    }
 
}

